networks:
  lilith-0:
    driver: bridge

volumes:
  lilith_db:
    driver: local

services:
  lilith_db:
    container_name: lilith_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 1433:1433
    env_file:
        - sqlenvironment.env
        - sqlpassword.env
    volumes:
      - lilith_db:/var/opt/mssql
    networks:
        - lilith-0
  lilith-0:
    container_name: lilith-0
    image: ${DOCKER_REGISTRY-}lilith0
    build:
      context: .
      dockerfile: Lilith-0/Dockerfile
    ports:
        - 8001:80
    depends_on: 
        - lilith_db
